export const NO_STREAM = "No stream";
export const WEBCAM = "Webcam";
export const SCREEN_SHARE = "Screen share";
export const VIDEO_WIDTH = 720;
export const VIDEO_HEIGHT = 480;
export const VIDEO_WIDTH_FULL = 1080;
export const VIDEO_HEIGHT_FULL = 720;
export const ROLE_USER = "role-user";
export const ROLE_PEER = "role-peer";